version: "3"
services:
  nginx:
    image: nginx
    ports: 
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
  passapi1:
    image: nicopaez/password-api
  passapi2:
    image: nicopaez/password-api

